# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e3a58814b53aadd7fe0174b4798ad60d2d6ba330c454aadb256c8b0c05614098c177c6ca0adedf2f8525c0c0fa9b4fd40ad9bb5828e55d3c314ffd336b9153a

test:
  secret_key_base: 12bcaf7e38cf8aacd3085523498d327be44762c0f0284933f06202d6e9324dee9c161b5109039eec141235e9dbb140c8eab48bd5aaa4f23e17f6a8ecc4ab5df9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
